# CMake generated Testfile for 
# Source directory: C:/__Dev/dcmtk-3.6.7/dcmtls/tests
# Build directory: C:/__Dev/dcmtk-3.6.7/vs2022/dcmtls/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmtls_scp_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/Debug/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/Debug/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmtls_scp_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/Release/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/Release/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmtls_scp_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/MinSizeRel/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/MinSizeRel/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmtls_scp_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/RelWithDebInfo/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/RelWithDebInfo/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
else()
  add_test(dcmtls_scp_tls NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmtls_scp_pool_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/Debug/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_pool_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_pool_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/Debug/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmtls_scp_pool_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/Release/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_pool_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_pool_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/Release/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmtls_scp_pool_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/MinSizeRel/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_pool_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_pool_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/MinSizeRel/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmtls_scp_pool_tls "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/vs2022/bin/RelWithDebInfo/dcmtls_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmtls_scp_pool_tls" "-P" "C:/__Dev/dcmtk-3.6.7/vs2022/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmtls_scp_pool_tls PROPERTIES  LABELS "dcmtls" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/vs2022/bin/RelWithDebInfo/dcmtls_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmtls/tests/CMakeLists.txt;0;")
else()
  add_test(dcmtls_scp_pool_tls NOT_AVAILABLE)
endif()
