# CMake generated Testfile for 
# Source directory: C:/__Dev/dcmtk-3.6.7/dcmfg/tests
# Build directory: C:/__Dev/dcmtk-3.6.7/build/dcmfg/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_concatenation_creator "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_concatenation_creator "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_concatenation_creator "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_concatenation_creator "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_concatenation_creator NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_concatenation_creator_fail "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator_fail" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator_fail PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_concatenation_creator_fail "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator_fail" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator_fail PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_concatenation_creator_fail "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator_fail" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator_fail PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_concatenation_creator_fail "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_creator_fail" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_creator_fail PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_concatenation_creator_fail NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_concatenation_loader "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_loader" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_loader PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_concatenation_loader "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_loader" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_loader PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_concatenation_loader "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_loader" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_loader PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_concatenation_loader "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_concatenation_loader" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_concatenation_loader PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_concatenation_loader NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_ct_image_frame_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_image_frame_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_image_frame_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_ct_image_frame_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_image_frame_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_image_frame_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_ct_image_frame_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_image_frame_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_image_frame_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_ct_image_frame_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_image_frame_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_image_frame_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_ct_image_frame_type NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_ct_acquisition_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_ct_acquisition_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_ct_acquisition_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_ct_acquisition_type "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_type" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_type PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_ct_acquisition_type NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_ct_acquisition_details "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_details" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_details PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_ct_acquisition_details "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_details" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_details PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_ct_acquisition_details "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_details" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_details PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_ct_acquisition_details "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_acquisition_details" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_acquisition_details PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_ct_acquisition_details NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_ct_table_dynamics "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_table_dynamics" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_table_dynamics PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_ct_table_dynamics "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_table_dynamics" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_table_dynamics PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_ct_table_dynamics "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_table_dynamics" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_table_dynamics PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_ct_table_dynamics "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_table_dynamics" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_table_dynamics PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_ct_table_dynamics NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_ct_position "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_position" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_position PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_ct_position "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_position" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_position PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_ct_position "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_position" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_position PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_ct_position "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_ct_position" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_ct_position PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_ct_position NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_derivation_image "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_derivation_image" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_derivation_image PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_derivation_image "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_derivation_image" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_derivation_image PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_derivation_image "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_derivation_image" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_derivation_image PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_derivation_image "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_derivation_image" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_derivation_image PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_derivation_image NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_frame_content "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_frame_content" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_frame_content PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_frame_content "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_frame_content" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_frame_content PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_frame_content "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_frame_content" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_frame_content PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_frame_content "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_frame_content" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_frame_content PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_frame_content NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmfg_irradiation_event_identification "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_irradiation_event_identification" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_irradiation_event_identification PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmfg_irradiation_event_identification "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_irradiation_event_identification" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_irradiation_event_identification PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmfg_irradiation_event_identification "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_irradiation_event_identification" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_irradiation_event_identification PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmfg_irradiation_event_identification "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmfg_irradiation_event_identification" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmfg_irradiation_event_identification PROPERTIES  LABELS "dcmfg" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmfg_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;20;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmfg/tests/CMakeLists.txt;0;")
else()
  add_test(dcmfg_irradiation_event_identification NOT_AVAILABLE)
endif()
