# CMake generated Testfile for 
# Source directory: C:/__Dev/dcmtk-3.6.7/dcmnet/tests
# Build directory: C:/__Dev/dcmtk-3.6.7/build/dcmnet/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_dimseDump_nullByte "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseDump_nullByte" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseDump_nullByte PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_dimseDump_nullByte "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseDump_nullByte" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseDump_nullByte PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_dimseDump_nullByte "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseDump_nullByte" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseDump_nullByte PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_dimseDump_nullByte "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseDump_nullByte" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseDump_nullByte PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_dimseDump_nullByte NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_dimseStatusClass "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseStatusClass" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseStatusClass PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_dimseStatusClass "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseStatusClass" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseStatusClass PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_dimseStatusClass "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseStatusClass" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseStatusClass PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_dimseStatusClass "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_dimseStatusClass" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_dimseStatusClass PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_dimseStatusClass NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_pool "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_pool" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_pool PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_pool "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_pool" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_pool PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_pool "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_pool" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_pool PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_pool "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_pool" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_pool PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_pool NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_builtin_verification_support "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_builtin_verification_support" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_builtin_verification_support PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_builtin_verification_support "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_builtin_verification_support" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_builtin_verification_support PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_builtin_verification_support "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_builtin_verification_support" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_builtin_verification_support PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_builtin_verification_support "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_builtin_verification_support" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_builtin_verification_support PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_builtin_verification_support NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_fail_on_invalid_association_configuration "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_invalid_association_configuration" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_invalid_association_configuration PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_fail_on_invalid_association_configuration "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_invalid_association_configuration" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_invalid_association_configuration PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_fail_on_invalid_association_configuration "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_invalid_association_configuration" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_invalid_association_configuration PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_fail_on_invalid_association_configuration "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_invalid_association_configuration" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_invalid_association_configuration PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_fail_on_invalid_association_configuration NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_fail_on_disallowed_host "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_disallowed_host" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_disallowed_host PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_fail_on_disallowed_host "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_disallowed_host" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_disallowed_host PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_fail_on_disallowed_host "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_disallowed_host" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_disallowed_host PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_fail_on_disallowed_host "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_fail_on_disallowed_host" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_fail_on_disallowed_host PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_fail_on_disallowed_host NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_stop_after_current_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_current_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_current_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_stop_after_current_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_current_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_current_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_stop_after_current_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_current_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_current_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_stop_after_current_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_current_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_current_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_stop_after_current_association NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_stop_after_timeout "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_timeout" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_timeout PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_stop_after_timeout "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_timeout" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_timeout PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_stop_after_timeout "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_timeout" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_timeout PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_stop_after_timeout "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_stop_after_timeout" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_stop_after_timeout PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_stop_after_timeout NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_no_stop_wo_request_noblock "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_noblock" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_noblock PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_no_stop_wo_request_noblock "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_noblock" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_noblock PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_no_stop_wo_request_noblock "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_noblock" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_noblock PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_no_stop_wo_request_noblock "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_noblock" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_noblock PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_no_stop_wo_request_noblock NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_no_stop_wo_request_block "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_block" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_block PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_no_stop_wo_request_block "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_block" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_block PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_no_stop_wo_request_block "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_block" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_block PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_no_stop_wo_request_block "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_stop_wo_request_block" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_stop_wo_request_block PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_no_stop_wo_request_block NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_no_term_notify_without_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_term_notify_without_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_term_notify_without_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_no_term_notify_without_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_term_notify_without_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_term_notify_without_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_no_term_notify_without_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_term_notify_without_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_term_notify_without_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_no_term_notify_without_association "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_no_term_notify_without_association" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_no_term_notify_without_association PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_no_term_notify_without_association NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scp_role_selection "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_role_selection" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_role_selection PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scp_role_selection "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_role_selection" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_role_selection PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scp_role_selection "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_role_selection" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_role_selection PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scp_role_selection "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scp_role_selection" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scp_role_selection PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scp_role_selection NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dcmnet_scu_session_handler "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scu_session_handler" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scu_session_handler PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Debug/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmnet_scu_session_handler "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scu_session_handler" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scu_session_handler PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/Release/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dcmnet_scu_session_handler "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scu_session_handler" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scu_session_handler PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/MinSizeRel/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dcmnet_scu_session_handler "C:/Program Files/CMake/bin/cmake.exe" "-DDCMTK_CTEST_TESTCASE_COMMAND=C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" "-DDCMTK_CTEST_TEST_NAME=dcmnet_scu_session_handler" "-P" "C:/__Dev/dcmtk-3.6.7/build/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmnet_scu_session_handler PROPERTIES  LABELS "dcmnet" REQUIRED_FILES "C:/__Dev/dcmtk-3.6.7/build/bin/RelWithDebInfo/dcmnet_tests.exe" _BACKTRACE_TRIPLES "C:/__Dev/dcmtk-3.6.7/CMake/dcmtkMacros.cmake;31;add_test;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;15;DCMTK_ADD_TESTS;C:/__Dev/dcmtk-3.6.7/dcmnet/tests/CMakeLists.txt;0;")
else()
  add_test(dcmnet_scu_session_handler NOT_AVAILABLE)
endif()
